language: python
sudo: false

python:
  - "3.6"

cache:
  pip: true

install:
  - python setup.py develop
  - pip install flake8

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

script:
  - python -m unittest tests/*.py -v
